spring:
  thymeleaf:
    prefix: classpath:templates/html/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

server:
  tomcat:
    uri-encoding: UTF-8
  port: 1010